import os
import sys
import argparse
import json
import yaml

# A placeholder map of frameworks to suggested testing skills
# This can be expanded as new frameworks are discovered or added.
FRAMEWORK_MAP = {
    "python": "test-python-pytest",
    "react": "test-react-jest",
    "node": "test-node-jest",
    "go": "test-go-test",
    "vue": "test-vue-vitest",
    "unknown": "test-generic-script"
}

def detect_framework(project_path):
    """
    Very simple detection logic.
    """
    # Python detection
    if os.path.exists(os.path.join(project_path, "requirements.txt")) or \
       os.path.exists(os.path.join(project_path, "pyproject.toml")) or \
       any(f.endswith(".py") for f in os.listdir(project_path)):
        return "python"
        
    # JS/TS detection
    package_json_path = os.path.join(project_path, "package.json")
    if os.path.exists(package_json_path):
        try:
            with open(package_json_path, "r", encoding="utf-8") as f:
                content = f.read().lower()
                if "react" in content:
                    return "react"
                elif "vue" in content:
                    return "vue"
                else:
                    return "node"
        except:
            return "node"
            
    # Go detection
    if os.path.exists(os.path.join(project_path, "go.mod")):
        return "go"
        
    return "unknown"

def generate_test_skill(framework, skill_name):
    """
    Generates a new testing skill template based on the framework.
    """
    skills_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    new_skill_dir = os.path.join(skills_root, skill_name)
    
    if os.path.exists(new_skill_dir):
        print(f"Skill {skill_name} already exists.")
        return

    os.makedirs(new_skill_dir)
    
    # Create skill.yaml
    skill_data = {
        "name": skill_name,
        "description": f"Testing skill for {framework} projects. Generated by test-architect.",
        "version": "1.0.0",
        "commands": [
            {
                "name": "run_tests",
                "description": f"Run tests for {framework}",
                "arguments": []
            }
        ]
    }
    
    with open(os.path.join(new_skill_dir, "skill.yaml"), "w", encoding="utf-8") as f:
        yaml.dump(skill_data, f, allow_unicode=True)

    # Create a basic implementation script
    script_content = f"""import os
import sys

def run_tests():
    print("Running tests for {framework}...")
    # TODO: Implement actual test runner logic based on best practices
    # e.g., subprocess.run(["pytest"]) for python
    
if __name__ == "__main__":
    run_tests()
"""
    with open(os.path.join(new_skill_dir, "test_runner.py"), "w", encoding="utf-8") as f:
        f.write(script_content)
        
    # Create README with instructions
    readme_content = f"""# {skill_name}

This skill was automatically generated by `test-architect`.

## Usage
`python .trae/skills/{skill_name}/test_runner.py`

## Implementation Steps (Manual or Agent)
1.  Check project dependencies (e.g., install pytest/jest).
2.  Update `test_runner.py` to execute the correct test command.
3.  Add test files to the project.
"""
    with open(os.path.join(new_skill_dir, "README.md"), "w", encoding="utf-8") as f:
        f.write(readme_content)

    print(f"Generated new skill: {skill_name} at {new_skill_dir}")

def architect_test(project_path):
    framework = detect_framework(project_path)
    skill_name = FRAMEWORK_MAP.get(framework, f"test-{framework}-generic")
    
    skills_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    target_skill_path = os.path.join(skills_root, skill_name)
    
    exists = os.path.exists(target_skill_path)
    
    result = {
        "framework": framework,
        "recommended_skill": skill_name,
        "exists": exists,
        "path": target_skill_path if exists else None,
        "action": "use" if exists else "create"
    }
    
    if not exists:
        print(f"Testing skill '{skill_name}' not found. Initiating creation process...")
        generate_test_skill(framework, skill_name)
        print(f"[REQUEST_SEARCH: best practices for testing {framework} projects]")
        print(f"Generated skeleton for {skill_name}. Please update test_runner.py with search results.")
        result["exists"] = True
        result["action"] = "created_needs_update"
        result["path"] = target_skill_path
        
    print(json.dumps(result, indent=2))

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--path", help="Path to the project root", default=os.getcwd())
    args = parser.parse_args()
    
    architect_test(args.path)
